# Generated by Django 3.2.6 on 2021-08-28 15:45

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('type_user', models.CharField(choices=[('cashier', 'Caixa'), ('waiter', 'Garçom'), ('manager', 'Gestor')], max_length=50, verbose_name='Tipo de Usuário')),
                ('changed_pass', models.BooleanField(default=False, verbose_name='Trocou senha?')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
