# Generated by Django 3.2.6 on 2021-09-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_user',
            field=models.CharField(choices=[('cashier', 'Caixa'), ('waiter', 'Garçom'), ('manager', 'Gerente')], max_length=50, verbose_name='Tipo de Usuário'),
        ),
    ]
