# Generated by Django 3.2.6 on 2021-08-29 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210828_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('departure_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de saída')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saída de Produto',
                'verbose_name_plural': 'Saída de Produtos',
            },
        ),
        migrations.CreateModel(
            name='InputOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Entrada de Produto',
                'verbose_name_plural': 'Entrada de Produtos',
            },
        ),
    ]
