# Generated by Django 3.2.6 on 2021-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_inputofproduct_outputofproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_measure',
            field=models.CharField(blank=True, choices=[('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro'), ('g', 'Grama')], max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
