# Generated by Django 3.2.6 on 2022-04-07 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_type_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_min',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Mínima'),
        ),
    ]
