# Generated by Django 3.2.6 on 2022-05-18 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_stock_quantity_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço de Compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('consumption', 'Consumo'), ('sale', 'Venda')], default='sale', max_length=11, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_measure',
            field=models.CharField(blank=True, choices=[('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro'), ('g', 'Grama'), ('un', 'Unidade')], max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor'),
        ),
    ]
