# Generated by Django 3.2.6 on 2021-10-25 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_itemsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total'),
        ),
    ]
