# Generated by Django 3.2.6 on 2021-10-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.card', verbose_name='Ficha'),
        ),
    ]
