# Generated by Django 3.2.6 on 2021-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_sale_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('closed', 'Fechada'), ('open', 'Aberto')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
