# Generated by Django 3.2.6 on 2021-10-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='sale.ItemSale', verbose_name='Itens da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type_of_payment',
            field=models.CharField(blank=True, choices=[('money', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'Pix')], max_length=50, null=True, verbose_name='Tipo de Pagamento'),
        ),
    ]
