# Generated by Django 3.2.6 on 2021-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20211027_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(blank=True, to='sale.ItemSale', verbose_name='Itens da Venda'),
        ),
    ]
