# Generated by Django 3.2.6 on 2021-10-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_sale_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.AddField(
            model_name='itemsale',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('closed', 'Fechada'), ('open', 'Aberto'), ('canceled', 'Cancelada')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
