# Generated by Django 3.2.6 on 2021-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20211027_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('closed', 'Fechada'), ('open', 'Aberta'), ('canceled', 'Cancelada')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
