# Generated by Django 3.2.6 on 2021-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20211125_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsale',
            name='status',
            field=models.CharField(blank=True, choices=[('canceled', 'Cancelada')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
